language: objective-c
matrix:
  include:
    # Xcode 9: iOS 11, macOS 10.13, tvOS 11, watchOS 4
    - osx_image: xcode9
      env:
        - SDK="iphonesimulator11.0"
        - SCHEME="HTMLReader iOS"
        - DESTINATION="OS=11.0,name=iPhone 8 Plus"
        - ACTION="test"
    - osx_image: xcode9
      env:
        - SDK="macosx10.13"
        - SCHEME="HTMLReader OS X"
        - DESTINATION="arch=x86_64"
        - ACTION="test"
    - osx_image: xcode9
      env:
        - SDK="appletvsimulator11.0"
        - SCHEME="HTMLReader tvOS"
        - DESTINATION="OS=11.0,name=Apple TV 4K"
        - ACTION="test"
    - osx_image: xcode9
      env:
        - SDK="watchsimulator4.0"
        - SCHEME="HTMLReader watchOS"
        - DESTINATION="OS=4.0,name=Apple Watch Series 3 - 42mm"
        - ACTION="build"
    # Xcode 8.3: iOS 10, macOS 10.12, tvOS 10, watchOS 3
    - osx_image: xcode8.3
      env:
        - SDK="iphonesimulator10.3"
        - SCHEME="HTMLReader iOS"
        - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"
        - ACTION="test"
    - osx_image: xcode8.3
      env:
        - SDK="macosx10.12"
        - SCHEME="HTMLReader OS X"
        - DESTINATION="arch=x86_64"
        - ACTION="test"
    - osx_image: xcode8.3
      env:
        - SDK="appletvsimulator10.2"
        - SCHEME="HTMLReader tvOS"
        - DESTINATION="OS=10.0,name=Apple TV 1080p"
        - ACTION="test"
    - osx_image: xcode8.3
      env:
        - SDK="watchsimulator3.2"
        - SCHEME="HTMLReader watchOS"
        - DESTINATION="OS=3.2,name=Apple Watch - 42mm"
        - ACTION="build"
    # Xcode 7.3: iOS 9, OS X 10.11, tvOS 9, watchOS 2
    - osx_image: xcode7.3
      env:
        - SDK="iphonesimulator9.3"
        - SCHEME="HTMLReader iOS"
        - DESTINATION="OS=9.0,name=iPhone 5"
        - ACTION="test"
    - osx_image: xcode7.3
      env:
        - SDK="macosx10.11"
        - SCHEME="HTMLReader OS X"
        - DESTINATION="arch=x86_64"
        - ACTION="test"
    - osx_image: xcode7.3
      env:
        - SDK="appletvsimulator9.2"
        - SCHEME="HTMLReader tvOS"
        - DESTINATION="OS=9.0,name=Apple TV 1080p"
        - ACTION="test"
    - osx_image: xcode7.3
      env:
        - SDK="watchsimulator2.2"
        - SCHEME="HTMLReader watchOS"
        - DESTINATION="OS=2.0,name=Apple Watch - 42mm"
        - ACTION="build"
    # Xcode 6.4: iOS 8, OS X 10.10, OS X 10.9
    - osx_image: xcode6.4
      env:
        - SDK="iphonesimulator8.4"
        - SCHEME="HTMLReader iOS"
        - DESTINATION="OS=8.4,name=iPhone 5s"
        - ACTION="test"
    - osx_image: xcode6.4
      env:
        - SDK="macosx10.10"
        - SCHEME="HTMLReader OS X"
        - DESTINATION="arch=x86_64"
        - ACTION="test"
    - osx_image: xcode6.4
      env:
        - SDK="macosx10.9"
        - SCHEME="HTMLReader OS X"
        - DESTINATION="arch=x86_64"
        - ACTION="test"
script:
  - xcodebuild -project HTMLReader.xcodeproj -scheme "$SCHEME" -configuration Release -sdk "$SDK" -destination "$DESTINATION" "$ACTION"
notifications:
  email:
    - nolan@nolanw.ca
