language: objective-c
before_install:
  - brew update
  - brew install xctool || brew upgrade xctool
env:
  - TEST_SDK=iphonesimulator8.0
  - TEST_SDK=iphonesimulator7.1
  - TEST_SDK=iphonesimulator7.0
  - TEST_SDK=macosx10.9 TEST_SCHEME="OS X"
script: xctool -project HTMLReader.xcodeproj -scheme "HTMLReader ${TEST_SCHEME:-iOS}" -sdk $TEST_SDK ${TEST_ACTION:-test}
notifications:
  email:
    - nolan@nolanw.ca
